# Generated by Django 3.2 on 2021-04-23 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=45)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Telegram token',
                'verbose_name_plural': 'Telegram tokens',
            },
        ),
        migrations.DeleteModel(
            name='TelegramToken',
        ),
    ]
